### ISSUE TITLE
Not working! Was working before v0.2.0

### ISSUE THREAD

**Issue by aPinix** [jodyheavener/circleci-vscode#4]
Was **working flawlessly** before this new **version 0.2.0**.

I'm using the correct **API token** from **CircleCi** but always gives me **"No workflow found"**.

![CleanShot 2020-10-27 at 10 35 50](https://user-images.githubusercontent.com/698523/97290432-741d8f80-1840-11eb-808f-7461a1779cba.png)

Can you help us all?

**Comment by jodyheavener** [comment]
@aPinix thanks for reporting, I can take a look. Here are a couple things that could help debug:

- When you start the extension is there any output in `Debug Console`?
- Do you have a Git remote set for `origin` (`git config --get remote.origin.url`)?
- Does the "Open in browser" button at the top take you to the correct Project in CircleCI?

**Comment by jodyheavener** [comment]
Is this issue still occurring?

**Comment by jodyheavener** [comment]
Going to close this issue as it appears inactive. Please re-open with the above requested details if the issue continues.
